
service: shareThePain

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
custom:
  envname:
    dev: arn:aws:execute-api:us-west-2:281941637822:8f49q59z0c
    int: int-sinclairstoryline
    qa: qa-sinclairstoryline
    stage: stage-sinclairstoryline
    prod: sinclairstoryline
    other: int-sinclairstoryline
provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
#  stage: dev
  region: us-west-2
  role: arn:aws:iam::281941637822:role/firebase-${opt:stage}-us-west-2-lambdaRole

  include:
    - pain_lambda.py
    - deps/**
  exclude:
    - test/**

functions:
  firebase:
    region: us-west-2
    handler: pain_lambda.handleRequest
    description: Basic API to record pain points
    memorySize: 128
    timeout: 30
    environment:
      stage: ${opt:stage}
      apiKey: 'AIzaSyAgJEKrEdc6Gv6Cwp3ANODIzymloPWJM_s'
      authDomain: 'intense-fire-8265.firebaseapp.com'
      databaseURL: 'https://intense-fire-8265.firebaseio.com'
      projectId: 'intense-fire-8265'
      storageBucket: 'intense-fire-8265.appspot.com'
      messagingSenderId: '301339768416'

resources:
 Resources:
  Yay:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: arn:aws:lambda:us-west-2:281941637822:function:shareThePain-${opt:stage}-firebase
      Principal: apigateway.amazonaws.com
      SourceArn: ${self:custom.envname.${opt:stage}, self:custom.envname.other}/*/POST/yay
  WTF:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: arn:aws:lambda:us-west-2:281941637822:function:shareThePain-${opt:stage}-firebase
      Principal: apigateway.amazonaws.com
      SourceArn: ${self:custom.envname.${opt:stage}, self:custom.envname.other}/*/POST/wtf
  SetReason:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: arn:aws:lambda:us-west-2:281941637822:function:shareThePain-${opt:stage}-firebase
      Principal: apigateway.amazonaws.com
      SourceArn: ${self:custom.envname.${opt:stage}, self:custom.envname.other}/*/POST/mux

